format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$status\
$line_break\
$character\
"""

add_newline = false

[status]
disabled = false
format = '[$status]($style) '

[directory]
fish_style_pwd_dir_length = 1

[git_branch]
format = 'on [$branch(:$remote_branch)]($style) '

